## 📊 **W14 - Oil Production**

## **Librerías**

In [2]:
import pandas as pd
import numpy as np

In [1]:
import plotly.express as px
import plotly.graph_objects as ga

## **Datos**

In [3]:
df = pd.read_csv('data/oil-production-by-country.csv')

In [22]:
df.sample(5)

                   Entity Code  Year         Oil
62                   Iraq  IRQ  1962   571.82385
380                 Qatar  QAT  1905     0.00000
318                  Oman  OMN  1968   139.19073
682  United Arab Emirates  ARE  1957     0.00000
859         United States  USA  2009  3751.68020

In [21]:
df.groupby(['Entity'])["Year"].count()

Entity
Iraq                    125
Norway                  125
Oman                    125
Qatar                   125
Saudi Arabia            125
United Arab Emirates    125
United States           125
Name: Year, dtype: int64

In [ ]:
df_resume = df[df['Year'].isin([1960, 1970, 1980, 1990, 2000, 2010, 2020, 2026])].copy()

     Entity Code  Year         Oil
185  Norway  NOR  1960     0.00000
195  Norway  NOR  1970     0.00000
205  Norway  NOR  1980   291.32720
215  Norway  NOR  1990   955.32367
225  Norway  NOR  2000  1813.76730
235  Norway  NOR  2010  1157.59920
245  Norway  NOR  2020  1077.11740

In [44]:
df_resume.query('Entity == "Norway"')

     Entity Code  Year         Oil
185  Norway  NOR  1960     0.00000
195  Norway  NOR  1970     0.00000
205  Norway  NOR  1980   291.32720
215  Norway  NOR  1990   955.32367
225  Norway  NOR  2000  1813.76730
235  Norway  NOR  2010  1157.59920
245  Norway  NOR  2020  1077.11740

In [ ]:
df_last_year = df.query('Year == 2020')
df_last_year

                   Entity Code  Year         Oil
120                  Iraq  IRQ  2020  2349.70020
245                Norway  NOR  2020  1077.11740
370                  Oman  OMN  2020   536.27155
495                 Qatar  QAT  2020   832.98980
620          Saudi Arabia  SAU  2020  6042.74900
745  United Arab Emirates  ARE  2020  1941.36710
870         United States  USA  2020  8298.50000

In [62]:
df_last_year['%_Oil'] = df_last_year['Oil'].apply(lambda x: round(x/df_last_year['Oil'].sum() * 100, 2))
df_last_year.sort_values('%_Oil', ascending=False)

C:\Users\jmart\AppData\Local\Temp\ipykernel_8092\4223712819.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

                   Entity Code  Year         Oil  %_Oil
870         United States  USA  2020  8298.50000  39.37
620          Saudi Arabia  SAU  2020  6042.74900  28.67
120                  Iraq  IRQ  2020  2349.70020  11.15
745  United Arab Emirates  ARE  2020  1941.36710   9.21
245                Norway  NOR  2020  1077.11740   5.11
495                 Qatar  QAT  2020   832.98980   3.95
370                  Oman  OMN  2020   536.27155   2.54

In [ ]:
df_norway = df_resume[df_resume["Entity"] == "Norway"]

fig = px.line(
    df_resume,
    x="Year",
    y="Oil",
    markers=True,  # 👈 esto agrega los puntos
    title="Oil Production Over Time - Norway"
)

fig.show()

In [46]:
df_norway = df[df["Entity"] == "Norway"]

fig = px.line(
    df_norway,
    x="Year",
    y="Oil",
    markers=True,  # 👈 esto agrega los puntos
    title="Oil Production Over Time - Norway"
)

fig.show()